app:
  host: "0.0.0.0"
  port: 9527
  debug: false
  secret_key: "4f7b1e8a-3f0d-4e9b-a9d2-2f4c8e1c7a55"

auth:
  enabled: true
  users:
    - username: "admin"
      password_hash: "pbkdf2:sha256:260000$b6Mbm5UoLr23rgUY$a7381f826d201855020d37757f14d14f23f8c514f8a606d121cccf5942a4ae72"
    - username: "gou.fucai2@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$Jg5rs6OWe4i9PNTL$bdbcde3af297a80e7d08e372932fa08844ea251b36eeb1989ceca7d71d2e39d8"
    - username: "su.tai@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$dC98Lj5ppyuEfH5Q$6448860961eff23d6cf67519497fd9e331600bc274a62228ba97364b705adee4"
    - username: "jiao.yanxiang@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$5C1BUZQaSk6qTAc8$01e18419f1fbcd8f30573b2ac5ee683f9129578e5ba7eceeee6045da0cf7e6f4"
    - username: "yao.guochang@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$Xmfe84HqFK3B2E0u$cd689f473d9dd921f780233d2b6d101b098c7dab67b112d9472e0dd9e7f79fa0"
    - username: "xie.zhou2@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$ScpBxzzK1g4xtpr2$c27c936f90d7ae64d92ff0de013e48ee210a2f4b7529325b9682d21f83f5298f"
    - username: "duan.fusen@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$6HoONooPpjxb8sTO$c161dbc4d52b36986f72279fd70965906db1fcb78c4493a487cbdd68e50510a8"
    - username: "sun.hao282@iwhalecloud.com"
      password_hash: "pbkdf2:sha256:260000$4dNecc7AGPIRe3lu$6ff9a0fde32a973116dc5f61280bcb38608b4772c03bb7d3a5d3f91ec9b895e1"

# 用户：admin，密码：A9v#K2m!Q7x@Lp
# 用户：gou.fucai2@iwhalecloud.com，密码：R7@kP2!mX9#q
# 用户：su.tai@iwhalecloud.com，密码：N4$wT8@cL1!v
# 用户：jiao.yanxiang@iwhalecloud.com，密码：Q9#eH3!rY7@u
# 用户：yao.guochang@iwhalecloud.com，密码：M2@zK8#pD5!n
# 用户：xie.zhou2@iwhalecloud.com，密码：V6!tR1@xJ9#b
# 用户：duan.fusen@iwhalecloud.com，密码：C3#mW7!qF2@k
# 用户：sun.hao282@iwhalecloud.com，密码：P8@nL4#sT6!y


logging:
  file: "logs/app.log"

tasks:
  # 查询类（状态查看）
  alb_rule_traffic:
    name: "查看 ALB 转发情况"
    type: "sh"
    cmd: "/bin/bash /root/sre-home/blue_green/alb_rule_traffic.sh"
    confirm: false

  check_middleware_switch:
    name: "查看中间件切换情况(SQL结果)"
    type: "sh"
    cmd: "/bin/bash /root/sre-home/blue_green/check_middleware_switch.sh"
    confirm: false

  # 中间件切换（sh）
  middleware_to_az1:
    name: "中间件切换到 AZ1"
    type: "sh"
    cmd: "/bin/bash /root/sre-home/blue_green/middleware_to_az1.sh"
    confirm: true

  middleware_to_az2:
    name: "中间件切换到 AZ2"
    type: "sh"
    cmd: "/bin/bash /root/sre-home/blue_green/middleware_to_az2.sh"
    confirm: true

  middleware_restore:
    name: "中间件恢复双机房"
    type: "sh"
    cmd: "/bin/bash /root/sre-home/blue_green/middleware.sh"
    confirm: true

  # ALB切流（jar）
  alb_to_az1:
    name: "ALB切流到 AZ1"
    type: "jar"
    cmd: "/usr/local/java/jdk1.8.0_411/bin/java -jar /root/sre-home/blue_green/BE-deploy-util.jar 1 0 0"
    confirm: true

  alb_to_az2:
    name: "ALB切流到 AZ2"
    type: "jar"
    cmd: "/usr/local/java/jdk1.8.0_411/bin/java -jar /root/sre-home/blue_green/BE-deploy-util.jar 0 1 0"
    confirm: true

  alb_restore:
    name: "ALB恢复双机房"
    type: "jar"
    cmd: "/usr/local/java/jdk1.8.0_411/bin/java -jar /root/sre-home/blue_green/BE-deploy-util.jar 0 0 1"
    confirm: true

did:
  scan_script: "/bin/bash /root/sre-home/blue_green/did-white/did-scan.sh"
  modify_script: "/bin/bash /root/sre-home/blue_green/did-white/did-modify.sh"
  priority_script: "/bin/bash /root/sre-home/blue_green/did-white/did-priority.sh"